---
# File: .github/workflows/template-sync.yml

on:
  # manual trigger
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Log changes without creating a PR'
        required: true
        type: boolean
        default: false
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: write
      pull-requests: write
      # Add this permission to allow changes to workflow files
      workflows: write


    steps:
      # - name: Generate a token
      #   id: generate_token
      #   # uses: actions/create-github-app-token@v1
      #   uses: tibdex/github-app-token@v2
      #   with:
      #     app_id: ${{ vars.APP_ID }}
      #     private_key: ${{ secrets.APP_PRIVATE_KEY }}
      #     # owner: KamilSacharczuk
      #     repositories: test_template,${{ github.event.repository.name }}

      - name: Checkout
        # https://github.com/actions/checkout#usage
        uses: actions/checkout@v4
        # with:
          # token: ${{ steps.generate_token.outputs.token }}

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          # source_gh_token: ${{ steps.generate_token.outputs.token }}
          source_repo_path: KamilSacharczuk/test_template
          upstream_branch: main
          pr_labels: dp_template,sync,test
          # target_gh_token: ${{ steps.generate_token.outputs.token }}
          is_dry_run: ${{ github.event.inputs.dry_run }}
